# Generated by Django 6.0.5 on 2026-06-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_lesson_transcribed_at_lesson_transcription_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzleprogress',
            name='attempts_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='puzzleprogress',
            name='hints_used',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='puzzleprogress',
            name='solve_time_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_puzzle_solved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='puzzle_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
