# Generated by Django 6.0.5 on 2026-07-29 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_puzzleprogress_attempts_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='courses/banners/'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.CharField(blank=True, help_text='e.g., 10 Hours', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='course',
            name='learning_outcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published'), ('Archived', 'Archived')], default='Draft', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma separated tags', max_length=255),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_flashcards',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_key_concepts',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_keywords',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='negative_marking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiz',
            name='shuffle_questions',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=0, help_text='Time limit in minutes, 0 means unlimited'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice'), ('MA', 'Multiple Answer'), ('TF', 'True/False'), ('FIB', 'Fill in Blank'), ('SA', 'Short Answer'), ('CODE', 'Coding Question'), ('IMG', 'Image Question')], default='MCQ', max_length=10),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateTimeField()),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('late_submission_rules', models.TextField(blank=True)),
                ('auto_close', models.BooleanField(default=False)),
                ('question_paper', models.FileField(blank=True, null=True, upload_to='assignments/questions/')),
                ('dataset', models.FileField(blank=True, null=True, upload_to='assignments/datasets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='LessonResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='lessons/resources/')),
                ('resource_type', models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('doc', 'Word Document'), ('image', 'Image'), ('zip', 'ZIP File'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='courses.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('meeting_link', models.URLField(max_length=500)),
                ('platform', models.CharField(choices=[('Zoom', 'Zoom'), ('Google Meet', 'Google Meet'), ('Microsoft Teams', 'Microsoft Teams'), ('Other', 'Other')], default='Zoom', max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('duration', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('max_students', models.PositiveIntegerField(default=100)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='assignments/submissions/')),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('assignment', 'student')},
            },
        ),
    ]
